INSERT INTO APPUSER(IDAPPUSER, BALANCE, PASSWORD, USERNAME) VALUES (1, 1000.0, '$2a$10$AJ5wugGhQ1ZJs4tdyvc9W.3M9Vp0JzyLca.bDTrbbLeDrKAhNeTSa', 'ra')

INSERT INTO APPUSER(IDAPPUSER, BALANCE, PASSWORD, USERNAME) VALUES (2, 1000.0, '$2a$10$DHSHbwupO.uTwdLDojovtOgVdN2.3q1YAXfOIepnzmBQrUpWydbpa', 'ta')

INSERT INTO APPUSER(IDAPPUSER, BALANCE, PASSWORD, USERNAME) VALUES (3, 1000.0, '$2a$10$8lBfJdIID8VWhIg5Ag0vxOgmJAGyhB9CS/9wn6MTbNuGy3nMbiCOy', 'od')

INSERT INTO APPUSER(IDAPPUSER, BALANCE, PASSWORD, USERNAME) VALUES (4, 1000.0, '$2a$10$mLSwDyORjFaAvQ9S92okMeYHbylkbeXGaQnj5FwDRm5UNmmOXclrS', 'ae')

